/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuditLogStorage } from "./AuditLogStorage";
export type { DIDCredentialStorage } from "./DIDCredentialStorage";
export type { KYCDataStorage } from "./KYCDataStorage";
export type { TenantConfigStorage } from "./TenantConfigStorage";
