/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MultisigModifierInterface extends Interface {
  getFunction(
    nameOrSignature: "multisigManager" | "owner" | "setMultisigManager"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MultisigManagerUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "multisigManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMultisigManager",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "multisigManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMultisigManager",
    data: BytesLike
  ): Result;
}

export namespace MultisigManagerUpdatedEvent {
  export type InputTuple = [oldManager: AddressLike, newManager: AddressLike];
  export type OutputTuple = [oldManager: string, newManager: string];
  export interface OutputObject {
    oldManager: string;
    newManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultisigModifier extends BaseContract {
  connect(runner?: ContractRunner | null): MultisigModifier;
  waitForDeployment(): Promise<this>;

  interface: MultisigModifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  multisigManager: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setMultisigManager: TypedContractMethod<
    [_multisigManager: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "multisigManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMultisigManager"
  ): TypedContractMethod<[_multisigManager: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MultisigManagerUpdated"
  ): TypedContractEvent<
    MultisigManagerUpdatedEvent.InputTuple,
    MultisigManagerUpdatedEvent.OutputTuple,
    MultisigManagerUpdatedEvent.OutputObject
  >;

  filters: {
    "MultisigManagerUpdated(address,address)": TypedContractEvent<
      MultisigManagerUpdatedEvent.InputTuple,
      MultisigManagerUpdatedEvent.OutputTuple,
      MultisigManagerUpdatedEvent.OutputObject
    >;
    MultisigManagerUpdated: TypedContractEvent<
      MultisigManagerUpdatedEvent.InputTuple,
      MultisigManagerUpdatedEvent.OutputTuple,
      MultisigManagerUpdatedEvent.OutputObject
    >;
  };
}
