/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AuditLogStorage__factory } from "./AuditLogStorage__factory";
export { DIDCredentialStorage__factory } from "./DIDCredentialStorage__factory";
export { KYCDataStorage__factory } from "./KYCDataStorage__factory";
export { TenantConfigStorage__factory } from "./TenantConfigStorage__factory";
