/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DIDManager__factory } from "./DIDManager__factory";
export { KYCManager__factory } from "./KYCManager__factory";
